# Generated by Django 4.2.11 on 2026-07-29 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosTarea',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.CharField(max_length=500)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'archivos_tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_planificadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'asignaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentariosTarea',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto_comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'comentarios_tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'historial_presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogsAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'logs_auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Archivado', 'Archivado')], default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'registro_horas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('IDEA', 'Idea'), ('POR_HACER', 'Por Hacer'), ('EN_CURSO', 'En Curso'), ('PRUEBAS', 'Pruebas'), ('FINALIZADO', 'Finalizado')], default='POR_HACER', max_length=20)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Gerente_Proyecto', 'Gerente de Proyecto'), ('Miembro_Equipo', 'Miembro del Equipo'), ('Ejecutivo', 'Ejecutivo')], default='Miembro_Equipo', max_length=30)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
